ROLE_RECRUITER = "Recruiter"
ROLE_HIRING_MANAGER = "Hiring Manager"
ROLE_HR_ADMIN = "HR Admin"

RECRUITMENT_ROLES = (
    ROLE_RECRUITER,
    ROLE_HR_ADMIN,
)

DASHBOARD_ROLES = (
    ROLE_RECRUITER,
    ROLE_HIRING_MANAGER,
    ROLE_HR_ADMIN,
)

SYSTEM_ROLES = (
    ROLE_RECRUITER,
    ROLE_HIRING_MANAGER,
    ROLE_HR_ADMIN,
)
