# Generated by Django 6.0.6 on 2026-10-09 13:54

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationnote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(models.F('candidate'), django.db.models.functions.text.Lower('imported_position'), condition=models.Q(('job__isnull', True)), name='unique_imported_application_per_candidate_position'),
        ),
    ]
