# Generated by Django 6.0.5 on 2026-07-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_candidate_company_jobopening_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('on_hold', 'On hold'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
