# Generated by Django 6.0.5 on 2026-07-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_alter_jobopening_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('hybrid', 'Hybrid'), ('contract', 'Contract'), ('internship', 'Internship')], default='full_time', max_length=20),
        ),
    ]
