# Generated by Django 6.0.5 on 2026-07-21 14:01

from django.conf import settings
from django.db import migrations, models


def copy_hiring_manager_to_hiring_managers(apps, schema_editor):
    JobOpening = apps.get_model("recruitment", "JobOpening")
    for job in JobOpening.objects.exclude(hiring_manager__isnull=True):
        job.hiring_managers.add(job.hiring_manager)


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_alter_jobopening_employment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='hiring_managers',
            field=models.ManyToManyField(blank=True, related_name='collaborating_job_openings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            copy_hiring_manager_to_hiring_managers,
            migrations.RunPython.noop,
        ),
    ]
