# Generated by Django 6.0.5 on 2026-07-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_jobopening_hiring_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobopening',
            name='hiring_manager',
        ),
        migrations.RemoveField(
            model_name='jobopening',
            name='hiring_managers',
        ),
    ]
